# Snakefile

# Regla para ejecutar el script de cálculo
rule calcular_indice:
    input:
        surface="R.midthickness.k.fix.surf.gii",
        mask="R.cortical.vertices.k.fix.shape.gii",
        data="R.NOISE_cubic_low_res_k.fix.func.gii"
    output:
        "full_brain_test.geig.vb-cluster.value.shape.gii",
        "full_brain_test.geig.vb-cluster.vector.shape.gii"
    shell:
        "./vb_index.py --surface {input.surface} --mask {input.mask} --data {input.data} --output full_brain_test --full-brain"
